import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.ksp)
    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.koin.compiler)
}

// Writes the backend address into commonMain as a generated Kotlin file, so the address is a
// build-time setting rather than a source constant. The value is the plexive.api.baseUrl Gradle
// property, whose committed default lives in gradle.properties.
abstract class GenerateApiConfig : DefaultTask() {

    @get:Input
    abstract val baseUrl: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val url = baseUrl.get().trim()
        if (url.isEmpty()) {
            throw GradleException(
                "plexive.api.baseUrl is missing or blank. Its default belongs in " +
                    "mobile-kmp/gradle.properties. Override it for this machine in " +
                    "~/.gradle/gradle.properties, or for one build with -Pplexive.api.baseUrl=..."
            )
        }
        val target = outputDir.get().asFile.resolve("com/plexive/mobile/core/network/ApiConfig.kt")
        target.parentFile.mkdirs()
        target.writeText(
            """
            package com.plexive.mobile.core.network

            // Generated by the generateApiConfig task in shared/build.gradle.kts. Do not edit: every
            // build overwrites it. The value is the plexive.api.baseUrl Gradle property. Read it
            // from nowhere but the HTTP client.
            const val API_BASE_URL = "$url"

            """.trimIndent()
        )
    }
}

// providers.gradleProperty rather than project.findProperty: it is the accessor Gradle documents as
// configuration-cache safe, so changing the property invalidates the cached configuration instead of
// silently reusing the previous URL. orElse("") keeps a missing property on the task's own error
// message rather than an unset-Property failure.
val generateApiConfig = tasks.register<GenerateApiConfig>("generateApiConfig") {
    baseUrl.set(providers.gradleProperty("plexive.api.baseUrl").orElse(""))
    outputDir.set(layout.buildDirectory.dir("generated/apiconfig/commonMain/kotlin"))
}

kotlin {
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    androidLibrary {
        namespace = "com.plexive.mobile.shared"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
        androidResources {
            enable = true
        }
        withHostTest {
            isIncludeAndroidResources = true
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
        }
        commonMain {
            // flatMap on the task's output carries the task dependency, so every target that
            // compiles commonMain generates the file first.
            kotlin.srcDir(generateApiConfig.flatMap { it.outputDir })

            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(libs.compose.ui)
                implementation(libs.compose.components.resources)
                implementation(libs.compose.uiToolingPreview)
                implementation(libs.androidx.lifecycle.viewmodelCompose)
                implementation(libs.androidx.lifecycle.runtimeCompose)
                implementation(libs.bundles.ktor)
                implementation(libs.androidx.nav3)
                implementation(libs.compose.viewmodelNavigation3)
                implementation(libs.bundles.koin)
            }
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

dependencies {
    androidRuntimeClasspath(libs.compose.uiTooling)
}
