import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.ksp)
    alias(libs.plugins.kotlinx.serialization)
    alias(libs.plugins.koin.compiler)
    alias(libs.plugins.ktlint)
    alias(libs.plugins.detekt)
}

// Writes the backend address into commonMain as a generated Kotlin file, so the address is a
// build-time setting rather than a source constant. The value is the plexive.api.baseUrl Gradle
// property, whose committed default lives in gradle.properties.
abstract class GenerateApiConfig : DefaultTask() {

    @get:Input
    abstract val baseUrl: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val url = baseUrl.get().trim()
        if (url.isEmpty()) {
            throw GradleException(
                "plexive.api.baseUrl is missing or blank. Its default belongs in " +
                    "mobile-kmp/gradle.properties. Override it for this machine in " +
                    "~/.gradle/gradle.properties, or for one build with -Pplexive.api.baseUrl=..."
            )
        }
        val target = outputDir.get().asFile.resolve("com/plexive/mobile/core/network/ApiConfig.kt")
        target.parentFile.mkdirs()
        target.writeText(
            """
            package com.plexive.mobile.core.network

            // Generated by the generateApiConfig task in shared/build.gradle.kts. Do not edit: every
            // build overwrites it. The value is the plexive.api.baseUrl Gradle property. Read it
            // from nowhere but the HTTP client.
            const val API_BASE_URL = "$url"

            """.trimIndent()
        )
    }
}

// providers.gradleProperty rather than project.findProperty: it is the accessor Gradle documents as
// configuration-cache safe, so changing the property invalidates the cached configuration instead of
// silently reusing the previous URL. orElse("") keeps a missing property on the task's own error
// message rather than an unset-Property failure.
val generateApiConfig = tasks.register<GenerateApiConfig>("generateApiConfig") {
    baseUrl.set(providers.gradleProperty("plexive.api.baseUrl").orElse(""))
    outputDir.set(layout.buildDirectory.dir("generated/apiconfig/commonMain/kotlin"))
}

kotlin {
    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    androidLibrary {
        namespace = "com.plexive.mobile.shared"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
        androidResources {
            enable = true
        }
        withHostTest {
            isIncludeAndroidResources = true
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
        }
        iosMain.dependencies {
            // Only iOS gets this: its KeychainSettings is the tested Keychain implementation nobody
            // here can write and verify. The Android half is hand-written against the Keystore,
            // because this library has no encrypted Android implementation and the one it documents
            // (EncryptedSharedPreferences) was deprecated in androidx.security 1.1.0.
            implementation(libs.multiplatform.settings)
        }
        commonMain {
            // flatMap on the task's output carries the task dependency, so every target that
            // compiles commonMain generates the file first.
            kotlin.srcDir(generateApiConfig.flatMap { it.outputDir })

            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.foundation)
                implementation(libs.compose.material3)
                implementation(libs.compose.ui)
                implementation(libs.compose.components.resources)
                implementation(libs.compose.uiToolingPreview)
                implementation(libs.androidx.lifecycle.viewmodelCompose)
                implementation(libs.androidx.lifecycle.runtimeCompose)
                implementation(libs.bundles.ktor)
                implementation(libs.androidx.nav3)
                implementation(libs.compose.viewmodelNavigation3)
                implementation(libs.bundles.koin)
            }
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

dependencies {
    androidRuntimeClasspath(libs.compose.uiTooling)
}

// Spike only: ktlint is evaluated here, not adopted.
ktlint {
    version.set(libs.versions.ktlintTool)
    // The KMP source set detection otherwise picks up generated Compose resource collectors under
    // build/, which are not ours to format and fail on a package name the generator chooses.
    filter {
        exclude { it.file.path.replace('\\', '/').contains("/build/") }
    }
}

// The jlleitschuh plugin wires ktlintCheck into the check lifecycle task, and it does so for each
// KMP source set as that source set is created, which is after this build script is evaluated.
// afterEvaluate is therefore the only point where every ktlint task already exists to be detached.
// The spike must leave no gate behind.
// Detaching ktlint from check via dependsOn filtering does not work on this KMP module: the
// hierarchy source sets (appleMain, nativeMain, iosTest) are materialized after both a plain and a
// nested afterEvaluate, so their ktlint tasks re-attach to check afterwards. configureEach applies
// to tasks created at any point, so the guard below is ordering-proof: ktlint runs only when it is
// asked for by name, and is skipped when reached through check. The spike leaves no gate behind.
tasks.matching { it.name.contains("ktlint", ignoreCase = true) }.configureEach {
    onlyIf {
        gradle.startParameter.taskNames.any { it.contains("ktlint", ignoreCase = true) }
    }
}

// Spike only: Detekt is evaluated here, not adopted. Same ordering-proof guard as ktlint, so Detekt
// runs only when asked for by name and never gates check.
detekt {
    buildUponDefaultConfig = true
    ignoreFailures = false
}
tasks.matching { it.name.contains("detekt", ignoreCase = true) }.configureEach {
    // Detekt 2.0.0-alpha.6 pulls generated Compose resource sources under build/ into its source
    // sets, which Detekt 1.23.8 did not. They are not ours to fix, so they are excluded here.
    // A plain exclude("**/build/**") does not work here: SourceTask patterns are matched against
    // paths relative to each source root, and the generated Compose roots are themselves inside
    // build/, so "build" never appears in the relative path. The absolute path is matched instead.
    if (this is SourceTask) {
        exclude { it.file.invariantSeparatorsPath.contains("/build/generated/") }
    }
    onlyIf {
        gradle.startParameter.taskNames.any { it.contains("detekt", ignoreCase = true) }
    }
}
