"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-08-28 18:46:39.502186

THIS FILE WAS REGENERATED IN PLACE ON 2026-08-28, KEEPING revision = '0001',
AND THAT WAS ONLY SAFE BECAUSE NOTHING HAD BEEN STAMPED YET. A revision id is a
claim about what a stamped database contains. While no database has ever
recorded '0001', no such claim exists and the id is free to be reused; the
regeneration was a documentation change, catching the baseline up with the
models.py reconciliation of the same day (docs/research/schema-drift-2026-08.md
section 6b).

ONCE `alembic stamp head` HAS RUN ANYWHERE, THAT STOPS BEING TRUE. From then on
a database asserts that it matches THIS revision id, and editing the file under
the id makes that assertion false without changing anything that could detect
it. After the stamp, a schema change is a NEW revision, never an edit here.

REVIEW THIS FILE BY HAND BEFORE RUNNING IT. If it was produced by
--autogenerate, it is a candidate, not a migration.

  AUTOGENERATE CANNOT DETECT A RENAME. A renamed column or table is rendered as
  a drop plus an add. Applied, that silently destroys the data in the old one.
  If you renamed something, replace both operations with a single
  op.alter_column(..., new_column_name=...) or op.rename_table(...).

Two more things autogenerate gets wrong in THIS repository specifically:

  - Partial indexes. models.py:144-151 declares uq_events_user_like with a
    postgresql_where predicate. Alembic 1.19.1 DID render that predicate
    correctly when creating the index from the metadata (measured 2026-08-28
    while generating this file), so this is a check rather than a known
    defect. Still read it: an index op that has lost its WHERE clause turns a
    partial unique index into a total one, which rejects rows the application
    expects to be able to write.

  - Type changes on populated columns. An ALTER TYPE rewrites the table. Never
    apply one you have not read, and never on production without a fresh dump
    (tools/backup_supabase.sh).
"""

from alembic import op
import sqlalchemy as sa  # noqa: F401 -- used by most but not all migrations
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Integer(), nullable=False),
    sa.Column('can_publish', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('avatar_frame_id', sa.Integer(), nullable=True),
    sa.Column('badge_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_rating', sa.Float(), nullable=True),
    sa.Column('knowledge_answered_count', sa.Integer(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('dm_key', sa.String(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_conversations_dm_key', 'conversations', ['dm_key'], unique=True)
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id', name='uq_follow')
    )
    op.create_index('ix_follows_following_id_status', 'follows', ['following_id', 'status'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('feed_card', sa.JSON(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('connections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('identity_key', sa.String(), nullable=True),
    sa.Column('reading_minutes', sa.Integer(), nullable=True),
    sa.Column('is_user_content', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_format'), 'posts', ['format'], unique=False)
    op.create_index(op.f('ix_posts_identity_key'), 'posts', ['identity_key'], unique=False)
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_index('ix_comments_post_id_created_at', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_table('conversation_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conversation_participant')
    )
    op.create_index(op.f('ix_conversation_participants_user_id'), 'conversation_participants', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index('ix_events_post_id_event_type', 'events', ['post_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_index('uq_events_user_like', 'events', ['user_id', 'post_id'], unique=True, postgresql_where=sa.text("event_type = 'like' AND user_id IS NOT NULL"), sqlite_where=sa.text("event_type = 'like' AND user_id IS NOT NULL"))
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_conversation_id_id', 'messages', ['conversation_id', 'id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('post_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_post_id', sa.Integer(), nullable=False),
    sa.Column('target_format', sa.String(), nullable=False),
    sa.Column('target_identity_key', sa.String(), nullable=False),
    sa.Column('target_post_id', sa.Integer(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['target_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_edges_source_post_id', 'post_edges', ['source_post_id'], unique=False)
    op.create_index('ix_post_edges_target_format_identity', 'post_edges', ['target_format', 'target_identity_key'], unique=False)
    op.create_index('ix_post_edges_target_post_id', 'post_edges', ['target_post_id'], unique=False)
    op.create_table('post_interests',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'interest_id')
    )
    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('chosen_index', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('rating_delta', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', 'question_index', name='uq_quiz_answer')
    )
    op.create_index(op.f('ix_quiz_answers_post_id'), 'quiz_answers', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_answers_post_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_table('post_interests')
    op.drop_index('ix_post_edges_target_post_id', table_name='post_edges')
    op.drop_index('ix_post_edges_target_format_identity', table_name='post_edges')
    op.drop_index('ix_post_edges_source_post_id', table_name='post_edges')
    op.drop_table('post_edges')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index('ix_messages_conversation_id_id', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index('uq_events_user_like', table_name='events', postgresql_where=sa.text("event_type = 'like' AND user_id IS NOT NULL"), sqlite_where=sa.text("event_type = 'like' AND user_id IS NOT NULL"))
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index('ix_events_post_id_event_type', table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_conversation_participants_user_id'), table_name='conversation_participants')
    op.drop_table('conversation_participants')
    op.drop_index('ix_comments_post_id_created_at', table_name='comments')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_index(op.f('ix_posts_identity_key'), table_name='posts')
    op.drop_index(op.f('ix_posts_format'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_follows_following_id_status', table_name='follows')
    op.drop_table('follows')
    op.drop_index('uq_conversations_dm_key', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('interests')
    # ### end Alembic commands ###
