import type { MarathonQuestion } from "@/types/train"

// PLACEHOLDER CONTENT -- replace with uploaded questions later.
//
// A hand-written pool of 100 HARD general-knowledge questions for the Arena and
// Battle duels (the solo Train marathon draws from the same pool). The earlier
// easy/starter pool was removed: every question here is meant to be genuinely
// difficult, so the three difficulty tiers now read as hard (1) / harder (2) /
// expert (3) rather than easy / medium / hard. The tier still maps to the Elo
// opponent rating (800/1000/1200) and to the Arena shot clock, so the spread is
// kept. The `topic` tag is coarse and informational only; nothing filters on it.
//
// Questions come in three kinds (see @/types/train): the default multiple-choice
// (options + answerIndex), `kind: "numeric"` (a number dialled in on a slider,
// with its own min/max limits, snap step and optional unit) and `kind: "map"`
// (drop a pin, graded by distance).
//
// ORDER IS LOAD-BEARING: this array must stay in the same order, with the same
// ids and answers, as the backend bank app/train_bank.py. Arena grades
// server-side and derives the question sequence from a shared seed, so a
// divergent pool silently mis-grades. Changing one side without the other is a
// bug (backend/tests/arena_test.py pins the parity).
//
// The answer (answerIndex / answerValue / answerLat+answerLng) is included here
// only because this is the mock phase; see the note at the top of @/types/train.

export const mockQuestions: MarathonQuestion[] = [
  // -------- Difficulty 1 (opponent rating 800): hard --------
  {
    id: "sci-krebs-location",
    prompt: "In eukaryotic cells, where does the citric acid (Krebs) cycle take place?",
    options: ["The cytosol", "The mitochondrial matrix", "The nucleus", "The Golgi apparatus"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "The Krebs cycle runs in the mitochondrial matrix; glycolysis is what happens in the cytosol.",
    topic: "science",
  },
  {
    id: "hist-westphalia-year",
    kind: "numeric",
    prompt: "In which year was the Peace of Westphalia signed?",
    answerValue: 1648,
    min: 1500,
    max: 1800,
    step: 1,
    difficulty: 1,
    explanation: "The 1648 treaties ended the Thirty Years' War and are seen as the start of the modern state system.",
    topic: "history",
  },
  {
    id: "lit-ulysses-author",
    prompt: "Who wrote the 1922 novel 'Ulysses'?",
    options: ["Virginia Woolf", "James Joyce", "T. S. Eliot", "Marcel Proust"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "James Joyce published 'Ulysses' in 1922; it follows a single day in Dublin.",
    topic: "literature",
  },
  {
    id: "sci-avogadro-exponent",
    prompt: "The Avogadro constant is closest to which order of magnitude?",
    options: ["10^21", "10^23", "10^25", "10^27"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "It is about 6.022 x 10^23 particles per mole.",
    topic: "science",
  },
  {
    id: "geo-deepest-trench",
    prompt: "Which ocean trench contains the deepest known point on Earth?",
    options: ["Puerto Rico Trench", "Mariana Trench", "Tonga Trench", "Java Trench"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "The Challenger Deep in the Mariana Trench reaches roughly 10,900 m.",
    topic: "geography",
  },
  {
    id: "math-derivative-lnx",
    prompt: "What is the derivative of ln(x) with respect to x?",
    options: ["x ln(x)", "1/x", "ln(x)/x", "e^x"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "d/dx ln(x) = 1/x for x > 0.",
    topic: "math",
  },
  {
    id: "econ-gini-meaning",
    prompt: "What does the Gini coefficient measure?",
    options: ["Inflation", "Income inequality", "Unemployment", "GDP growth"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "It ranges from 0 (perfect equality) to 1 (one person holds all income).",
    topic: "economics",
  },
  {
    id: "sci-dna-base-pair-adenine",
    prompt: "In double-stranded DNA, adenine pairs with which base?",
    options: ["Guanine", "Thymine", "Cytosine", "Uracil"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "A pairs with T in DNA; uracil replaces thymine only in RNA.",
    topic: "science",
  },
  {
    id: "hist-magna-carta-year",
    kind: "numeric",
    prompt: "In which year was Magna Carta sealed?",
    answerValue: 1215,
    min: 1100,
    max: 1400,
    step: 1,
    difficulty: 1,
    explanation: "King John sealed Magna Carta at Runnymede in 1215.",
    topic: "history",
  },
  {
    id: "lang-algebra-origin",
    prompt: "The word 'algebra' comes from which language?",
    options: ["Greek", "Arabic", "Latin", "Sanskrit"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "From the Arabic 'al-jabr', in the title of al-Khwarizmi's 9th-century treatise.",
    topic: "language",
  },
  {
    id: "sci-carbon14-halflife",
    kind: "numeric",
    prompt: "What is the half-life of carbon-14, in years?",
    answerValue: 5730,
    min: 1000,
    max: 12000,
    step: 10,
    unit: " yr",
    difficulty: 1,
    explanation: "About 5,730 years, which is what makes radiocarbon dating useful up to ~50,000 years.",
    topic: "science",
  },
  {
    id: "music-bach-period",
    prompt: "Johann Sebastian Bach belongs to which musical period?",
    options: ["Renaissance", "Baroque", "Classical", "Romantic"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "Bach (1685-1750) is the emblematic composer of the late Baroque.",
    topic: "music",
  },
  {
    id: "cs-quicksort-average",
    prompt: "What is the average-case time complexity of quicksort?",
    options: ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "Quicksort averages O(n log n); its worst case is O(n^2) on bad pivots.",
    topic: "computing",
  },
  {
    id: "geo-doubly-landlocked",
    prompt: "Which of these countries is doubly landlocked (all its neighbours are landlocked too)?",
    options: ["Nepal", "Uzbekistan", "Bolivia", "Mongolia"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "Only Uzbekistan and Liechtenstein are doubly landlocked.",
    topic: "geography",
  },
  {
    id: "sci-ph-hcl",
    kind: "numeric",
    prompt: "What is the pH of a 0.01 mol/L solution of hydrochloric acid?",
    answerValue: 2,
    min: 0,
    max: 14,
    step: 0.5,
    difficulty: 1,
    explanation: "HCl fully dissociates, so pH = -log10(0.01) = 2.",
    topic: "science",
  },
  {
    id: "art-guernica-painter",
    prompt: "Who painted 'Guernica' (1937)?",
    options: ["Salvador Dali", "Pablo Picasso", "Joan Miro", "Georges Braque"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "Picasso painted it in response to the bombing of the Basque town of Gernika.",
    topic: "art",
  },
  {
    id: "sci-quartz-mohs",
    kind: "numeric",
    prompt: "What is the hardness of quartz on the Mohs scale?",
    answerValue: 7,
    min: 1,
    max: 10,
    step: 1,
    difficulty: 1,
    explanation: "Quartz sits at 7, between orthoclase (6) and topaz (8); diamond is 10.",
    topic: "science",
  },
  {
    id: "lang-medieval-lingua-franca",
    prompt: "Which language served as the scholarly lingua franca of medieval Western Europe?",
    options: ["Greek", "Latin", "French", "Aramaic"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "Latin was the shared language of the church, universities and diplomacy.",
    topic: "language",
  },
  {
    id: "geo-hormuz-connects",
    prompt: "The Strait of Hormuz connects which two bodies of water?",
    options: [
      "The Red Sea and the Mediterranean",
      "The Persian Gulf and the Gulf of Oman",
      "The Black Sea and the Aegean",
      "The Baltic and the North Sea",
    ],
    answerIndex: 1,
    difficulty: 1,
    explanation: "It is the only sea route out of the Persian Gulf, which is why it is a chokepoint for oil.",
    topic: "geography",
  },
  {
    id: "sci-neutral-particle",
    prompt: "Which of these subatomic particles carries no electric charge?",
    options: ["Proton", "Neutron", "Electron", "Positron"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "The neutron is electrically neutral; the positron is the electron's positive antiparticle.",
    topic: "science",
  },
  {
    id: "hist-moonwalkers-count",
    kind: "numeric",
    prompt: "How many humans have walked on the surface of the Moon?",
    answerValue: 12,
    min: 0,
    max: 30,
    step: 1,
    difficulty: 1,
    explanation: "Twelve, all during the Apollo programme between 1969 and 1972.",
    topic: "history",
  },
  {
    id: "phil-categorical-imperative",
    prompt: "Which philosopher formulated the categorical imperative?",
    options: ["David Hume", "Immanuel Kant", "Friedrich Nietzsche", "John Locke"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "Kant set it out in the 'Groundwork of the Metaphysics of Morals' (1785).",
    topic: "philosophy",
  },
  {
    id: "cs-tcp-osi-layer",
    kind: "numeric",
    prompt: "At which layer of the OSI model does TCP operate?",
    answerValue: 4,
    min: 1,
    max: 7,
    step: 1,
    difficulty: 1,
    explanation: "TCP is the transport layer, layer 4; IP sits below it at layer 3.",
    topic: "computing",
  },
  {
    id: "sci-universal-blood-donor",
    prompt: "Which blood type is the universal red-cell donor?",
    options: ["AB positive", "O negative", "A negative", "B positive"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "O negative red cells carry no A, B or RhD antigens, so almost anyone can receive them.",
    topic: "science",
  },
  {
    id: "geo-most-time-zones",
    prompt: "Which country spans the most time zones?",
    options: ["Russia", "France", "United States", "China"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "Counting overseas territories, France covers 12 time zones; Russia has 11.",
    topic: "geography",
  },
  {
    id: "hist-hundred-years-war-length",
    kind: "numeric",
    prompt: "How many years did the Hundred Years' War actually last?",
    answerValue: 116,
    min: 50,
    max: 150,
    step: 1,
    difficulty: 1,
    explanation: "From 1337 to 1453, so 116 years despite the name.",
    topic: "history",
  },
  {
    id: "lit-1984-published",
    kind: "numeric",
    prompt: "In which year was George Orwell's 'Nineteen Eighty-Four' published?",
    answerValue: 1949,
    min: 1930,
    max: 1970,
    step: 1,
    difficulty: 1,
    explanation: "Published in June 1949, the year before Orwell died.",
    topic: "literature",
  },
  {
    id: "sci-atomic-number-7",
    prompt: "Which element has atomic number 7?",
    options: ["Carbon", "Nitrogen", "Oxygen", "Fluorine"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "Nitrogen has 7 protons; carbon has 6 and oxygen 8.",
    topic: "science",
  },
  {
    id: "math-factorial-seven",
    kind: "numeric",
    prompt: "What is 7! (seven factorial)?",
    answerValue: 5040,
    min: 0,
    max: 10000,
    step: 10,
    difficulty: 1,
    explanation: "7 x 6 x 5 x 4 x 3 x 2 x 1 = 5,040.",
    topic: "math",
  },
  {
    id: "geo-largest-lake",
    prompt: "Which is the largest lake in the world by surface area?",
    options: ["Lake Superior", "The Caspian Sea", "Lake Victoria", "Lake Baikal"],
    answerIndex: 1,
    difficulty: 1,
    explanation: "The Caspian Sea is an enclosed salt lake of about 371,000 km2.",
    topic: "geography",
  },

  // -------- Difficulty 2 (opponent rating 1000): harder --------
  {
    id: "sci-uncertainty-pair",
    prompt: "Heisenberg's uncertainty principle links the precision of which pair of quantities?",
    options: [
      "Energy and charge",
      "Position and momentum",
      "Mass and velocity",
      "Spin and charge",
    ],
    answerIndex: 1,
    difficulty: 2,
    explanation: "The better you know a particle's position, the less precisely its momentum is defined.",
    topic: "science",
  },
  {
    id: "hist-versailles-year",
    kind: "numeric",
    prompt: "In which year was the Treaty of Versailles signed?",
    answerValue: 1919,
    min: 1900,
    max: 1950,
    step: 1,
    difficulty: 2,
    explanation: "Signed on 28 June 1919, five years to the day after the assassination in Sarajevo.",
    topic: "history",
  },
  {
    id: "cs-hash-collision-chaining",
    prompt: "Which data structure classically resolves collisions by chaining?",
    options: ["Binary heap", "Hash table", "Trie", "Skip list"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Chaining stores colliding keys in a list at the same hash bucket.",
    topic: "computing",
  },
  {
    id: "sci-mitochondria-ancestor",
    prompt: "According to endosymbiotic theory, mitochondria descend from which group?",
    options: ["Archaea", "Alphaproteobacteria", "Viruses", "Fungi"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "An ancestral alphaproteobacterium was engulfed by a host cell and kept as an organelle.",
    topic: "science",
  },
  {
    id: "geo-fourteen-borders",
    prompt: "Which of these countries shares a land border with 14 other countries?",
    options: ["Brazil", "Russia", "India", "Germany"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Russia and China each border 14 countries, the most of any state.",
    topic: "geography",
  },
  {
    id: "math-euler-identity",
    prompt: "What is the value of e^(i x pi)?",
    options: ["1", "-1", "0", "i"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Euler's identity: e^(i pi) + 1 = 0, so e^(i pi) = -1.",
    topic: "math",
  },
  {
    id: "lit-churchill-nobel",
    prompt: "Winston Churchill won a Nobel Prize in which category?",
    options: ["Peace", "Literature", "Economic Sciences", "Physiology or Medicine"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "He won the 1953 Nobel Prize in Literature, largely for his historical writing and oratory.",
    topic: "literature",
  },
  {
    id: "sci-speed-of-sound",
    kind: "numeric",
    prompt: "Roughly how fast does sound travel in dry air at 20 C, in metres per second?",
    answerValue: 343,
    min: 0,
    max: 1000,
    step: 1,
    unit: " m/s",
    difficulty: 2,
    explanation: "About 343 m/s; the speed rises with temperature.",
    topic: "science",
  },
  {
    id: "hist-constantinople-fell",
    kind: "numeric",
    prompt: "In which year did Constantinople fall to the Ottomans?",
    answerValue: 1453,
    min: 1300,
    max: 1600,
    step: 1,
    difficulty: 2,
    explanation: "Mehmed II took the city in 1453, ending the Byzantine Empire.",
    topic: "history",
  },
  {
    id: "econ-stagflation",
    prompt: "What does 'stagflation' describe?",
    options: [
      "Falling prices with strong growth",
      "High inflation together with stagnant growth and high unemployment",
      "Rapid growth with full employment",
      "A fixed exchange rate under pressure",
    ],
    answerIndex: 1,
    difficulty: 2,
    explanation: "The combination defined the 1970s oil-shock economies and broke the simple Phillips curve.",
    topic: "economics",
  },
  {
    id: "sci-enzyme-suffix",
    prompt: "Enzyme names conventionally end in which suffix?",
    options: ["-ose", "-ase", "-ol", "-ine"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Lactase, protease, polymerase; '-ose' marks sugars instead (lactose, glucose).",
    topic: "science",
  },
  {
    id: "geo-atacama-country",
    prompt: "The Atacama Desert lies mainly in which country?",
    options: ["Peru", "Chile", "Argentina", "Bolivia"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Northern Chile; parts of it are the driest non-polar places on Earth.",
    topic: "geography",
  },
  {
    id: "cs-acid-isolation",
    prompt: "In database transactions, what does the 'I' in ACID stand for?",
    options: ["Integrity", "Isolation", "Indexing", "Immutability"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Atomicity, Consistency, Isolation, Durability.",
    topic: "computing",
  },
  {
    id: "sci-receding-galaxies",
    prompt: "Light from galaxies receding from us is shifted how?",
    options: ["Blueshifted", "Redshifted", "Unshifted", "Polarised"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Recession stretches the wavelength towards the red end, the basis of Hubble's law.",
    topic: "science",
  },
  {
    id: "hist-rosetta-scripts",
    kind: "numeric",
    prompt: "How many different scripts appear on the Rosetta Stone?",
    answerValue: 3,
    min: 1,
    max: 6,
    step: 1,
    difficulty: 2,
    explanation: "Hieroglyphic, Demotic and Ancient Greek, which is what allowed the decipherment.",
    topic: "history",
  },
  {
    id: "lang-cyrillic-namesake",
    prompt: "The Cyrillic alphabet is named after whom?",
    options: ["Cyrus the Great", "Saint Cyril", "The city of Cyrene", "Cyril of Alexandria"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Saint Cyril, the 9th-century missionary; his followers devised the script named for him.",
    topic: "language",
  },
  {
    id: "math-golden-ratio",
    kind: "numeric",
    prompt: "What is the value of the golden ratio, to three decimal places?",
    answerValue: 1.618,
    min: 0,
    max: 5,
    step: 0.001,
    difficulty: 2,
    explanation: "(1 + sqrt(5)) / 2 = 1.6180339...",
    topic: "math",
  },
  {
    id: "sci-largest-internal-organ",
    prompt: "What is the largest internal organ of the human body?",
    options: ["Lungs", "Liver", "Stomach", "Kidneys"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "The liver, at roughly 1.5 kg; the skin is larger but is not internal.",
    topic: "science",
  },
  {
    id: "hist-bronze-alloy",
    prompt: "Bronze is an alloy of copper and which other metal?",
    options: ["Zinc", "Tin", "Lead", "Iron"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Copper plus tin gives bronze; copper plus zinc gives brass.",
    topic: "history",
  },
  {
    id: "geo-prime-meridian",
    prompt: "The prime meridian passes through which observatory?",
    options: ["Paris", "Greenwich", "Cadiz", "Rome"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "The Royal Observatory, Greenwich was fixed as 0 degrees longitude in 1884.",
    topic: "geography",
  },
  {
    id: "sci-planck-magnitude",
    prompt: "The Planck constant is closest to which order of magnitude, in joule-seconds?",
    options: ["10^-30", "10^-34", "10^-38", "10^-42"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "It is exactly 6.62607015 x 10^-34 J s by definition since the 2019 SI redefinition.",
    topic: "science",
  },
  {
    id: "cs-rsa-hardness",
    prompt: "RSA encryption rests on the difficulty of which problem?",
    options: [
      "Sorting large arrays",
      "Factoring large integers",
      "Colouring graphs",
      "Inverting matrices",
    ],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Multiplying two large primes is easy; recovering them from the product is not.",
    topic: "computing",
  },
  {
    id: "hist-cuban-missile-crisis",
    kind: "numeric",
    prompt: "In which year did the Cuban Missile Crisis take place?",
    answerValue: 1962,
    min: 1945,
    max: 1990,
    step: 1,
    difficulty: 2,
    explanation: "October 1962, the closest the Cold War came to nuclear war.",
    topic: "history",
  },
  {
    id: "lit-divine-comedy-parts",
    kind: "numeric",
    prompt: "Into how many parts is Dante's 'Divine Comedy' divided?",
    answerValue: 3,
    min: 1,
    max: 6,
    step: 1,
    difficulty: 2,
    explanation: "Inferno, Purgatorio and Paradiso.",
    topic: "literature",
  },
  {
    id: "sci-scurvy-vitamin",
    prompt: "A deficiency of which vitamin causes scurvy?",
    options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "Vitamin C (ascorbic acid) is needed to build collagen.",
    topic: "science",
  },
  {
    id: "geo-longest-land-border",
    prompt: "Which pair of countries shares the longest land border in the world?",
    options: ["Russia and China", "Canada and the United States", "Argentina and Chile", "Kazakhstan and Russia"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "About 8,891 km, including the Alaska stretch.",
    topic: "geography",
  },
  {
    id: "math-birthday-paradox",
    kind: "numeric",
    prompt: "How many people are needed for a better-than-even chance that two share a birthday?",
    answerValue: 23,
    min: 2,
    max: 100,
    step: 1,
    difficulty: 2,
    explanation: "With 23 people the probability passes 50 percent, which is why it is called a paradox.",
    topic: "math",
  },
  {
    id: "sci-red-cell-lifespan",
    kind: "numeric",
    prompt: "About how many days does a human red blood cell live?",
    answerValue: 120,
    min: 1,
    max: 365,
    step: 5,
    unit: " days",
    difficulty: 2,
    explanation: "Roughly 120 days, after which the spleen recycles it.",
    topic: "science",
  },
  {
    id: "hist-gutenberg-press",
    kind: "numeric",
    prompt: "Around which year did Gutenberg introduce movable-type printing in Europe?",
    answerValue: 1440,
    min: 1300,
    max: 1600,
    step: 5,
    difficulty: 2,
    explanation: "About 1440; the Gutenberg Bible followed around 1455.",
    topic: "history",
  },
  {
    id: "lang-esperanto-creator",
    prompt: "Who created Esperanto?",
    options: ["J. R. R. Tolkien", "L. L. Zamenhof", "Noam Chomsky", "Ferdinand de Saussure"],
    answerIndex: 1,
    difficulty: 2,
    explanation: "The Polish ophthalmologist L. L. Zamenhof published it in 1887.",
    topic: "language",
  },

  // -------- Difficulty 3 (opponent rating 1200): expert --------
  {
    id: "cs-utf8-max-bytes",
    kind: "numeric",
    prompt: "What is the maximum number of bytes a single UTF-8 code point can use?",
    answerValue: 4,
    min: 1,
    max: 8,
    step: 1,
    difficulty: 3,
    explanation: "UTF-8 uses 1 to 4 bytes; it was capped at 4 to match the Unicode range.",
    topic: "computing",
  },
  {
    id: "sci-most-abundant-noble-gas",
    prompt: "Which noble gas is most abundant in Earth's atmosphere?",
    options: ["Helium", "Argon", "Neon", "Krypton"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "Argon makes up about 0.93 percent of air, far more than the other noble gases.",
    topic: "science",
  },
  {
    id: "geo-nile-basin-countries",
    kind: "numeric",
    prompt: "How many countries lie within the Nile river basin?",
    answerValue: 11,
    min: 1,
    max: 20,
    step: 1,
    difficulty: 3,
    explanation: "Eleven, from Burundi and Rwanda through Ethiopia, Sudan and Egypt.",
    topic: "geography",
  },
  {
    id: "math-riemann-critical-line",
    kind: "numeric",
    prompt: "The Riemann hypothesis says all non-trivial zeros have which real part?",
    answerValue: 0.5,
    min: 0,
    max: 2,
    step: 0.1,
    difficulty: 3,
    explanation: "They are conjectured to lie on the critical line Re(s) = 1/2.",
    topic: "math",
  },
  {
    id: "hist-defenestration-prague",
    kind: "numeric",
    prompt: "In which year did the Second Defenestration of Prague trigger the Thirty Years' War?",
    answerValue: 1618,
    min: 1500,
    max: 1700,
    step: 1,
    difficulty: 3,
    explanation: "In 1618 Protestant nobles threw imperial officials from a castle window; all survived.",
    topic: "history",
  },
  {
    id: "cs-halting-problem",
    prompt: "Who proved that the halting problem is undecidable?",
    options: ["Kurt Godel", "Alan Turing", "Alonzo Church", "Georg Cantor"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "Turing proved it in 1936 using a diagonal argument over Turing machines.",
    topic: "computing",
  },
  {
    id: "sci-cmb-temperature",
    kind: "numeric",
    prompt: "What is the temperature of the cosmic microwave background, in kelvin?",
    answerValue: 2.7,
    min: 0,
    max: 10,
    step: 0.1,
    unit: " K",
    difficulty: 3,
    explanation: "About 2.725 K, the cooled afterglow of the early universe.",
    topic: "science",
  },
  {
    id: "lit-lost-time-author",
    prompt: "Who wrote 'In Search of Lost Time'?",
    options: ["Andre Gide", "Marcel Proust", "Albert Camus", "Gustave Flaubert"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "Proust's seven-volume novel appeared between 1913 and 1927.",
    topic: "literature",
  },
  {
    id: "math-eulers-number",
    kind: "numeric",
    prompt: "What is Euler's number e, to three decimal places?",
    answerValue: 2.718,
    min: 0,
    max: 5,
    step: 0.001,
    difficulty: 3,
    explanation: "e = 2.718281828..., the base of the natural logarithm.",
    topic: "math",
  },
  {
    id: "sci-dna-unwinding-enzyme",
    prompt: "Which enzyme unwinds the DNA double helix during replication?",
    options: ["Ligase", "Helicase", "Polymerase", "Primase"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "Helicase separates the strands; polymerase then copies each one.",
    topic: "science",
  },
  {
    id: "geo-highest-capital",
    prompt: "Which is the highest capital city in the world by elevation?",
    options: ["Quito", "La Paz", "Bogota", "Thimphu"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "La Paz, Bolivia's seat of government, sits at about 3,600 m.",
    topic: "geography",
  },
  {
    id: "hist-rome-sacked-410",
    kind: "numeric",
    prompt: "In which year did the Visigoths under Alaric sack Rome?",
    answerValue: 410,
    min: 200,
    max: 700,
    step: 5,
    difficulty: 3,
    explanation: "In 410 CE, the first time Rome had fallen to a foreign enemy in 800 years.",
    topic: "history",
  },
  {
    id: "phil-veil-of-ignorance",
    prompt: "Which philosopher introduced the 'veil of ignorance'?",
    options: ["Robert Nozick", "John Rawls", "Amartya Sen", "Jurgen Habermas"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "Rawls used it in 'A Theory of Justice' (1971) to derive fair principles.",
    topic: "philosophy",
  },
  {
    id: "sci-fermi-paradox",
    prompt: "The Fermi paradox concerns the apparent absence of what?",
    options: ["Dark matter", "Extraterrestrial civilisations", "Quantum gravity", "Antimatter"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "If the galaxy should be full of civilisations, as Fermi asked: where is everybody?",
    topic: "science",
  },
  {
    id: "cs-millennium-prize",
    kind: "numeric",
    prompt: "How many US dollars does the Clay Institute offer for solving P versus NP?",
    answerValue: 1000000,
    min: 0,
    max: 5000000,
    step: 100000,
    unit: " USD",
    difficulty: 3,
    explanation: "One million dollars, as for each of the seven Millennium Prize Problems.",
    topic: "computing",
  },
  {
    id: "sci-strongest-force",
    prompt: "Which of the four fundamental forces is the strongest at short range?",
    options: ["Gravity", "The strong nuclear force", "Electromagnetism", "The weak nuclear force"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "The strong force binds quarks; gravity is by far the weakest of the four.",
    topic: "science",
  },
  {
    id: "lang-finnish-family",
    prompt: "Finnish belongs to which language family?",
    options: ["Indo-European", "Uralic", "Turkic", "Semitic"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "Finnish, Estonian and Hungarian are Uralic, unrelated to their Indo-European neighbours.",
    topic: "language",
  },
  {
    id: "math-reals-uncountable",
    prompt: "In set theory, the set of real numbers is:",
    options: ["Countably infinite", "Uncountably infinite", "Finite", "Empty"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "Cantor's diagonal argument shows the reals cannot be listed one by one.",
    topic: "math",
  },
  {
    id: "hist-first-circumnavigation",
    kind: "numeric",
    prompt: "In which year did the first circumnavigation of the globe finish?",
    answerValue: 1522,
    min: 1450,
    max: 1600,
    step: 1,
    difficulty: 3,
    explanation: "Elcano brought the Victoria home in 1522; Magellan had died in the Philippines.",
    topic: "history",
  },
  {
    id: "sci-molar-volume-stp",
    kind: "numeric",
    prompt: "What volume in litres does one mole of an ideal gas occupy at 0 C and 1 atm?",
    answerValue: 22.4,
    min: 0,
    max: 50,
    step: 0.1,
    unit: " L",
    difficulty: 3,
    explanation: "About 22.4 litres, the classic molar volume at standard temperature and pressure.",
    topic: "science",
  },
  {
    id: "geo-major-tectonic-plates",
    kind: "numeric",
    prompt: "How many major tectonic plates are usually counted?",
    answerValue: 7,
    min: 1,
    max: 20,
    step: 1,
    difficulty: 3,
    explanation: "Seven: African, Antarctic, Eurasian, Indo-Australian, North American, Pacific and South American.",
    topic: "geography",
  },
  {
    id: "econ-keynes-recession",
    prompt: "In a deep recession, Keynesian economics prescribes which response?",
    options: [
      "Cutting government spending to balance the budget",
      "Increasing government spending to raise demand",
      "Raising interest rates sharply",
      "Fixing the exchange rate to gold",
    ],
    answerIndex: 1,
    difficulty: 3,
    explanation: "Keynes argued deficient demand should be filled by public spending until private demand recovers.",
    topic: "economics",
  },
  {
    id: "sci-crispr-enzyme",
    prompt: "Which enzyme is most associated with CRISPR gene editing?",
    options: ["Taq polymerase", "Cas9", "Luciferase", "Reverse transcriptase"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "Cas9 cuts DNA at the site specified by a guide RNA.",
    topic: "science",
  },
  {
    id: "lit-waste-land-author",
    prompt: "Who wrote the poem 'The Waste Land' (1922)?",
    options: ["Ezra Pound", "T. S. Eliot", "W. B. Yeats", "W. H. Auden"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "Eliot wrote it; Pound edited the manuscript heavily.",
    topic: "literature",
  },
  {
    id: "cs-turing-award",
    prompt: "Which prize is known as the 'Nobel Prize of computing'?",
    options: ["The Fields Medal", "The Turing Award", "The Abel Prize", "The Dirac Medal"],
    answerIndex: 1,
    difficulty: 3,
    explanation: "The ACM A. M. Turing Award, given annually since 1966.",
    topic: "computing",
  },
  {
    id: "sci-absolute-zero-celsius",
    kind: "numeric",
    prompt: "What is absolute zero in degrees Celsius?",
    answerValue: -273.15,
    min: -300,
    max: 0,
    step: 0.05,
    unit: " C",
    difficulty: 3,
    explanation: "0 K equals -273.15 C, the point where thermal motion is minimal.",
    topic: "science",
  },
  {
    id: "hist-suez-crisis",
    kind: "numeric",
    prompt: "In which year did the Suez Crisis take place?",
    answerValue: 1956,
    min: 1930,
    max: 1980,
    step: 1,
    difficulty: 3,
    explanation: "1956, after Nasser nationalised the Suez Canal Company.",
    topic: "history",
  },
  {
    id: "sci-lanthanide-count",
    kind: "numeric",
    prompt: "How many elements are in the lanthanide series?",
    answerValue: 15,
    min: 5,
    max: 30,
    step: 1,
    difficulty: 3,
    explanation: "Fifteen, from lanthanum (57) to lutetium (71).",
    topic: "science",
  },

  // -------- Map picker: drop a pin, graded by distance (see @/lib/train/scoring) --------
  // These MUST stay in the same order (and with the same ids/answers) as the
  // backend bank app/train_bank.py: Arena grades server-side and derives the
  // question sequence from a shared seed, so a divergent pool silently mis-grades.
  {
    id: "geo-map-machu-picchu",
    kind: "map",
    prompt: "Drop a pin on Machu Picchu.",
    answerLat: -13.1631,
    answerLng: -72.545,
    answerLabel: "Cusco Region, Peru",
    difficulty: 2,
    explanation: "The Inca citadel sits on a ridge above the Urubamba valley in southern Peru.",
    topic: "geography",
  },
  {
    id: "geo-map-petra",
    kind: "map",
    prompt: "Where is the rock-cut city of Petra?",
    answerLat: 30.3285,
    answerLng: 35.4444,
    answerLabel: "Ma'an Governorate, Jordan",
    difficulty: 3,
    explanation: "Petra was the Nabataean capital, in what is now southern Jordan.",
    topic: "geography",
  },
  {
    id: "geo-map-angkor-wat",
    kind: "map",
    prompt: "Locate Angkor Wat.",
    answerLat: 13.4125,
    answerLng: 103.867,
    answerLabel: "Siem Reap, Cambodia",
    difficulty: 3,
    explanation: "The 12th-century temple complex lies near Siem Reap in northern Cambodia.",
    topic: "geography",
  },
  {
    id: "geo-map-easter-island",
    kind: "map",
    prompt: "Drop a pin on Easter Island (Rapa Nui).",
    answerLat: -27.1127,
    answerLng: -109.3497,
    answerLabel: "Rapa Nui, Chile",
    difficulty: 3,
    explanation: "One of the most remote inhabited islands on Earth, some 3,500 km west of Chile.",
    topic: "geography",
  },
  {
    id: "geo-map-timbuktu",
    kind: "map",
    prompt: "Where is Timbuktu?",
    answerLat: 16.7666,
    answerLng: -3.0026,
    answerLabel: "Tombouctou Region, Mali",
    difficulty: 3,
    explanation: "A medieval trans-Saharan trade and scholarship hub on the edge of the desert in Mali.",
    topic: "geography",
  },
  {
    id: "geo-map-ushuaia",
    kind: "map",
    prompt: "Locate Ushuaia, one of the southernmost cities in the world.",
    answerLat: -54.8019,
    answerLng: -68.303,
    answerLabel: "Tierra del Fuego, Argentina",
    difficulty: 3,
    explanation: "Ushuaia sits on the Beagle Channel in Argentine Tierra del Fuego.",
    topic: "geography",
  },
  {
    id: "geo-map-reykjavik",
    kind: "map",
    prompt: "Drop a pin on Reykjavik.",
    answerLat: 64.1466,
    answerLng: -21.9426,
    answerLabel: "Iceland",
    difficulty: 2,
    explanation: "The world's northernmost capital of a sovereign state, in south-west Iceland.",
    topic: "geography",
  },
  {
    id: "geo-map-cape-good-hope",
    kind: "map",
    prompt: "Where is the Cape of Good Hope?",
    answerLat: -34.3568,
    answerLng: 18.474,
    answerLabel: "Western Cape, South Africa",
    difficulty: 2,
    explanation: "On the Cape Peninsula south of Cape Town, South Africa.",
    topic: "geography",
  },
  {
    id: "geo-map-everest",
    kind: "map",
    prompt: "Locate the summit of Mount Everest.",
    answerLat: 27.9881,
    answerLng: 86.925,
    answerLabel: "Nepal / China border",
    difficulty: 2,
    explanation: "Everest straddles the border between Nepal and Tibet in the Himalaya.",
    topic: "geography",
  },
  {
    id: "geo-map-vladivostok",
    kind: "map",
    prompt: "Drop a pin on Vladivostok.",
    answerLat: 43.1155,
    answerLng: 131.8855,
    answerLabel: "Primorsky Krai, Russia",
    difficulty: 3,
    explanation: "Russia's Pacific port and the eastern end of the Trans-Siberian Railway.",
    topic: "geography",
  },
  {
    id: "geo-map-astana",
    kind: "map",
    prompt: "Where is Astana, the capital of Kazakhstan?",
    answerLat: 51.1694,
    answerLng: 71.4491,
    answerLabel: "Kazakhstan",
    difficulty: 3,
    explanation: "Astana lies on the steppe of northern Kazakhstan and became the capital in 1997.",
    topic: "geography",
  },
  {
    id: "geo-map-galapagos",
    kind: "map",
    prompt: "Locate the Galapagos Islands.",
    answerLat: -0.75,
    answerLng: -90.3167,
    answerLabel: "Galapagos, Ecuador",
    difficulty: 3,
    explanation: "About 900 km off the coast of Ecuador, where Darwin gathered evidence for natural selection.",
    topic: "geography",
  },
]
