// GENERATED by dark-equivalents.mjs beside this file. Do not edit by hand.
//
// Regenerate with:  node src/app/specimen/dark-equivalents.mjs emit
//
// It exists so the specimen page and the standalone offline file are fed by
// one computation. A hex typed into the page by hand is a hex that can drift
// from the script that justified it, and nothing on the page would show it.

export interface DarkEqColour {
  format: string
  hex: string
  oklch: string
  contrast: number
  clears: boolean
  impossible: boolean | null
  distanceToCounterpart: number
  note: string
}

export interface DarkEqLight {
  format: string
  hex: string
  oklch: string
  contrast: number
  clears: boolean
}

export interface DarkEqScores {
  minPairwiseDistance: number
  minPairwiseBetween: string
  minChroma: number
  minChromaFormat: string
  failures: number
  impossible: number
  maxDistanceToCounterpart: number
  meanDistanceToCounterpart: number
}

export interface DarkEqSet {
  key: string
  name: string
  blurb: string
  colours: DarkEqColour[]
  scores: DarkEqScores
}

export interface DarkEqData {
  lightGround: string
  lightGroundLine: number
  darkGround: string
  darkGroundLine: number
  floor: number
  formats: string[]
  light: DarkEqLight[]
  sets: DarkEqSet[]
}

export const DARK_EQ_DATA: DarkEqData = {
  "lightGround": "#F5ECDB",
  "lightGroundLine": 137,
  "darkGround": "#0D0F17",
  "darkGroundLine": 61,
  "floor": 3,
  "formats": [
    "books",
    "facts",
    "people",
    "concepts",
    "questions",
    "stories",
    "academy"
  ],
  "light": [
    {
      "format": "books",
      "hex": "#AF8100",
      "oklch": "oklch(0.6315 0.1298 83.34)",
      "contrast": 3.0025,
      "clears": true
    },
    {
      "format": "facts",
      "hex": "#0083FF",
      "oklch": "oklch(0.6215 0.2074 255.38)",
      "contrast": 3.1462,
      "clears": true
    },
    {
      "format": "people",
      "hex": "#F600DB",
      "oklch": "oklch(0.6677 0.2974 334.65)",
      "contrast": 3.0133,
      "clears": true
    },
    {
      "format": "concepts",
      "hex": "#8B00FF",
      "oklch": "oklch(0.5429 0.2939 297.50)",
      "contrast": 5.0549,
      "clears": true
    },
    {
      "format": "questions",
      "hex": "#009899",
      "oklch": "oklch(0.6158 0.1050 195.60)",
      "contrast": 3.0084,
      "clears": true
    },
    {
      "format": "stories",
      "hex": "#FF001E",
      "oklch": "oklch(0.6290 0.2563 26.93)",
      "contrast": 3.3968,
      "clears": true
    },
    {
      "format": "academy",
      "hex": "#009D55",
      "oklch": "oklch(0.6105 0.1552 153.62)",
      "contrast": 3.007,
      "clears": true
    }
  ],
  "sets": [
    {
      "key": "E1",
      "name": "E1 identical",
      "blurb": "The same hex as the light value. Takes the requirement literally.",
      "colours": [
        {
          "format": "books",
          "hex": "#AF8100",
          "oklch": "oklch(0.6315 0.1298 83.34)",
          "contrast": 5.4316,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0,
          "note": "same hex as the light value"
        },
        {
          "format": "facts",
          "hex": "#0083FF",
          "oklch": "oklch(0.6215 0.2074 255.38)",
          "contrast": 5.1835,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0,
          "note": "same hex as the light value"
        },
        {
          "format": "people",
          "hex": "#F600DB",
          "oklch": "oklch(0.6677 0.2974 334.65)",
          "contrast": 5.4121,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0,
          "note": "same hex as the light value"
        },
        {
          "format": "concepts",
          "hex": "#8B00FF",
          "oklch": "oklch(0.5429 0.2939 297.50)",
          "contrast": 3.2262,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0,
          "note": "same hex as the light value"
        },
        {
          "format": "questions",
          "hex": "#009899",
          "oklch": "oklch(0.6158 0.1050 195.60)",
          "contrast": 5.421,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0,
          "note": "same hex as the light value"
        },
        {
          "format": "stories",
          "hex": "#FF001E",
          "oklch": "oklch(0.6290 0.2563 26.93)",
          "contrast": 4.8011,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0,
          "note": "same hex as the light value"
        },
        {
          "format": "academy",
          "hex": "#009D55",
          "oklch": "oklch(0.6105 0.1552 153.62)",
          "contrast": 5.4235,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0,
          "note": "same hex as the light value"
        }
      ],
      "scores": {
        "minPairwiseDistance": 0.1044,
        "minPairwiseBetween": "questions / academy",
        "minChroma": 0.105,
        "minChromaFormat": "questions",
        "failures": 0,
        "impossible": 0,
        "maxDistanceToCounterpart": 0,
        "meanDistanceToCounterpart": 0
      }
    },
    {
      "key": "E2",
      "name": "E2 mirrored",
      "blurb": "Hue and chroma held from the light value; lightness set so the OKLCH lightness gap to #0D0F17 equals the gap the light value has to #F5ECDB, lighter than its ground.",
      "colours": [
        {
          "format": "books",
          "hex": "#7A5900",
          "oklch": "oklch(0.4856 0.0998 83.44)",
          "contrast": 2.9663,
          "clears": false,
          "impossible": false,
          "distanceToCounterpart": 0.149,
          "note": "chroma reduced 0.1298 -> 0.0995 (by 0.0302) to fit sRGB at L 0.4844"
        },
        {
          "format": "facts",
          "hex": "#005FBC",
          "oklch": "oklch(0.4945 0.1648 255.34)",
          "contrast": 3.0634,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.134,
          "note": "chroma reduced 0.2074 -> 0.1650 (by 0.0424) to fit sRGB at L 0.4944"
        },
        {
          "format": "people",
          "hex": "#900080",
          "oklch": "oklch(0.4485 0.1999 334.48)",
          "contrast": 2.275,
          "clears": false,
          "impossible": false,
          "distanceToCounterpart": 0.2399,
          "note": "chroma reduced 0.2974 -> 0.1997 (by 0.0977) to fit sRGB at L 0.4482"
        },
        {
          "format": "concepts",
          "hex": "#9134FF",
          "oklch": "oklch(0.5736 0.2711 297.56)",
          "contrast": 3.7703,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.0382,
          "note": "chroma reduced 0.2939 -> 0.2714 (by 0.0225) to fit sRGB at L 0.5730"
        },
        {
          "format": "questions",
          "hex": "#007273",
          "oklch": "oklch(0.5002 0.0853 195.84)",
          "contrast": 3.3289,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.1172,
          "note": "chroma reduced 0.1050 -> 0.0853 (by 0.0197) to fit sRGB at L 0.5001"
        },
        {
          "format": "stories",
          "hex": "#B50012",
          "oklch": "oklch(0.4863 0.1981 26.91)",
          "contrast": 2.7085,
          "clears": false,
          "impossible": false,
          "distanceToCounterpart": 0.1541,
          "note": "chroma reduced 0.2563 -> 0.1984 (by 0.0579) to fit sRGB at L 0.4869"
        },
        {
          "format": "academy",
          "hex": "#007940",
          "oklch": "oklch(0.5053 0.1286 153.56)",
          "contrast": 3.4696,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.1085,
          "note": "chroma reduced 0.1552 -> 0.1284 (by 0.0267) to fit sRGB at L 0.5054"
        }
      ],
      "scores": {
        "minPairwiseDistance": 0.0872,
        "minPairwiseBetween": "questions / academy",
        "minChroma": 0.0853,
        "minChromaFormat": "questions",
        "failures": 3,
        "impossible": 0,
        "maxDistanceToCounterpart": 0.2399,
        "meanDistanceToCounterpart": 0.1344
      }
    },
    {
      "key": "E3",
      "name": "E3 today",
      "blurb": "The seven values the app ships today, read from globals.css this run.",
      "colours": [
        {
          "format": "books",
          "hex": "#CFA857",
          "oklch": "oklch(0.7505 0.1097 83.86)",
          "contrast": 8.555,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.1207,
          "note": "globals.css line 102"
        },
        {
          "format": "facts",
          "hex": "#7EB1F3",
          "oklch": "oklch(0.7507 0.1102 255.25)",
          "contrast": 8.6264,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.1617,
          "note": "globals.css line 103"
        },
        {
          "format": "people",
          "hex": "#D993CA",
          "oklch": "oklch(0.7498 0.1101 334.64)",
          "contrast": 8.1769,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.2045,
          "note": "globals.css line 104"
        },
        {
          "format": "concepts",
          "hex": "#B69FEB",
          "oklch": "oklch(0.7506 0.1098 297.61)",
          "contrast": 8.3328,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.2776,
          "note": "globals.css line 105"
        },
        {
          "format": "questions",
          "hex": "#43C3C4",
          "oklch": "oklch(0.7491 0.1096 195.82)",
          "contrast": 8.9649,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.1334,
          "note": "globals.css line 106"
        },
        {
          "format": "stories",
          "hex": "#EB9288",
          "oklch": "oklch(0.7491 0.1096 26.89)",
          "contrast": 8.1976,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.1896,
          "note": "globals.css line 107"
        },
        {
          "format": "academy",
          "hex": "#73C28D",
          "oklch": "oklch(0.7488 0.1099 153.60)",
          "contrast": 8.9544,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.1455,
          "note": "globals.css line 108"
        }
      ],
      "scores": {
        "minPairwiseDistance": 0.0698,
        "minPairwiseBetween": "people / concepts",
        "minChroma": 0.1096,
        "minChromaFormat": "stories",
        "failures": 0,
        "impossible": 0,
        "maxDistanceToCounterpart": 0.2776,
        "meanDistanceToCounterpart": 0.1761
      }
    },
    {
      "key": "E4",
      "name": "E4 brighter",
      "blurb": "Hue and chroma held from the light value; lightness set to the value whose WCAG contrast against #0D0F17 is closest to 6.0.",
      "colours": [
        {
          "format": "books",
          "hex": "#B78915",
          "oklch": "oklch(0.6572 0.1300 83.60)",
          "contrast": 6.0143,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.0258,
          "note": "chroma held at 0.1298"
        },
        {
          "format": "facts",
          "hex": "#3490FF",
          "oklch": "oklch(0.6564 0.1857 255.55)",
          "contrast": 5.9931,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.0412,
          "note": "chroma reduced 0.2074 -> 0.1854 (by 0.0220) to fit sRGB at L 0.6570"
        },
        {
          "format": "people",
          "hex": "#FF22E3",
          "oklch": "oklch(0.6935 0.2953 334.73)",
          "contrast": 6.0029,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.0259,
          "note": "chroma reduced 0.2974 -> 0.2957 (by 0.0017) to fit sRGB at L 0.6935"
        },
        {
          "format": "concepts",
          "hex": "#A774FF",
          "oklch": "oklch(0.6740 0.1993 297.75)",
          "contrast": 5.9985,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.1616,
          "note": "chroma reduced 0.2939 -> 0.1988 (by 0.0951) to fit sRGB at L 0.6740"
        },
        {
          "format": "questions",
          "hex": "#1AA0A1",
          "oklch": "oklch(0.6416 0.1048 195.68)",
          "contrast": 6,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.0258,
          "note": "chroma held at 0.1050"
        },
        {
          "format": "stories",
          "hex": "#FF534B",
          "oklch": "oklch(0.6787 0.2095 26.93)",
          "contrast": 6.0037,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.0683,
          "note": "chroma reduced 0.2563 -> 0.2099 (by 0.0464) to fit sRGB at L 0.6782"
        },
        {
          "format": "academy",
          "hex": "#1AA55D",
          "oklch": "oklch(0.6361 0.1544 153.74)",
          "contrast": 5.9974,
          "clears": true,
          "impossible": null,
          "distanceToCounterpart": 0.0256,
          "note": "chroma held at 0.1552"
        }
      ],
      "scores": {
        "minPairwiseDistance": 0.1038,
        "minPairwiseBetween": "questions / academy",
        "minChroma": 0.1048,
        "minChromaFormat": "questions",
        "failures": 0,
        "impossible": 0,
        "maxDistanceToCounterpart": 0.1616,
        "meanDistanceToCounterpart": 0.0534
      }
    }
  ]
}
