"use client"

// THE DARK-EQUIVALENTS PANEL. Part of the temporary specimen surface at
// /specimen, not part of the product, and meant to be deleted with the rest of
// it.
//
// THE QUESTION IT SERVES. The seven light-ground accents are settled. What is
// open is what their equivalents are on the dark ground, and the requirement is
// that they are THE SAME SEVEN COLOURS READING THE SAME WAY -- not that they
// carry the same hex. Four answers are defensible, so four are shown and none
// is ranked.
//
// WHY THE LIGHT HALF HAS NO CONTROLS. It is settled. A control on it would
// invite a decision that has already been made, and the only reason it is on
// screen at all is that the dark half has to be compared against something
// other than a memory.
//
// THE TWO HALVES SHARE ONE ROW BUILDER, deliberately. The whole file is only
// useful if a colour and its equivalent sit vertically above each other, and
// two row builders are two things that can drift apart. probe-viewport.mjs
// measures the left edge and width of every .accrow in both halves and reports
// the worst disagreement, so the alignment is a number rather than an intention.
//
// THE ELEMENT IDS ARE halfLightEq AND halfDarkEq, NOT halfLight AND halfDark.
// ground-pair-panel.tsx already carries that second pair, and both panels render
// on /specimen at once. Duplicate ids are invalid HTML and getElementById returns
// only the FIRST, so probe-viewport.mjs would have measured the older panel while
// printing numbers that read as though they were about this one. The probe takes
// the id pair as arguments 4 and 5 for exactly this reason.
//
// EVERY VALUE COMES FROM dark-equivalents-data.ts, which is generated by
// dark-equivalents.mjs beside this file and never edited by hand. Nothing here
// computes a colour. The same blob feeds the standalone offline file on the
// desktop, so the page and that file cannot disagree about a hex.

import { useState } from "react"

import { DARK_EQ_DATA, type DarkEqColour, type DarkEqLight } from "./dark-equivalents-data"

// One short line of the reading face per half. The reading face is settled, so
// the article text is not the question here; the line exists only so each
// ground is seen as a page ground rather than as a swatch.
const BODY =
  "Walking in the snow with her nephew Otto Frisch, Lise Meitner did the sum on a scrap of paper."

const READING_STACK = "SpecEBGaramond, serif"

// The two text inks, the same two the standalone file uses.
const LIGHT_INK = "#1A1710"
const DARK_INK = "#E9E6DF"

// Chrome, deliberately neutral and deliberately labelled with its own hexes:
// this strip is not part of the specimen and must never be mistaken for it.
const CHROME_BG = "#1B1B1B"
const CHROME_INK = "#E8E8E8"
const CHROME_DIM = "#A0A0A0"
const CHROME_HEX = "#8A8A8A"
const CHROME_BTN = "#262626"
const CHROME_BTN_EDGE = "#3A3A3A"
const CHROME_BTN_ON_INK = "#141414"

const monoStyle: React.CSSProperties = {
  fontFamily: "ui-monospace, monospace",
  fontSizeAdjust: "none",
  fontSize: "0.625rem",
  lineHeight: 1.4,
  overflowWrap: "anywhere",
}

const sansStyle: React.CSSProperties = {
  fontFamily: "system-ui, sans-serif",
  fontSizeAdjust: "none",
}

// The row grid. minmax(0, ...) on every column: without the 0 minimum a grid
// column refuses to shrink below its content and the page gains a horizontal
// scrollbar on a narrow phone.
const rowStyle: React.CSSProperties = {
  display: "grid",
  gridTemplateColumns: "minmax(0, 1fr) minmax(0, 116px)",
  gap: "0.5rem",
  alignItems: "center",
}

export default function DarkEquivalentsPanel({ xheight }: { xheight: string }) {
  const D = DARK_EQ_DATA
  const [setIndex, setSetIndex] = useState(0)
  const active = D.sets[setIndex]

  const button = (label: string, on: boolean, onClick: () => void) => (
    <button
      key={label}
      type="button"
      onClick={onClick}
      aria-pressed={on}
      style={{
        ...sansStyle,
        minHeight: "44px",
        padding: "0.375rem 0.75rem",
        borderRadius: "0.5rem",
        border: "1px solid " + (on ? CHROME_INK : CHROME_BTN_EDGE),
        background: on ? CHROME_INK : CHROME_BTN,
        color: on ? CHROME_BTN_ON_INK : "#C8C8C8",
        fontSize: "0.75rem",
        fontWeight: on ? 600 : 400,
        lineHeight: 1.2,
        textAlign: "left",
        cursor: "pointer",
      }}
    >
      {label}
    </button>
  )

  // ONE row builder for both halves. `extra` is the third line on a dark row,
  // which is the OKLab distance to the light value directly above it.
  const row = (c: DarkEqColour | DarkEqLight, ink: string, extra: string | null) => {
    const clears = c.clears
    const impossible = "impossible" in c ? c.impossible : null
    return (
      <div className="accrow" key={c.format} style={rowStyle}>
        {clears ? (
          <div style={{ display: "flex", alignItems: "center", gap: "0.5rem", minWidth: 0 }}>
            <span style={{ width: "28px", height: "2px", flex: "none", background: c.hex }} />
            <span style={{ width: "12px", height: "12px", flex: "none", background: c.hex }} />
            <span
              style={{
                ...sansStyle,
                fontSize: "0.6875rem",
                letterSpacing: "0.04em",
                textTransform: "uppercase",
                color: ink,
                overflowWrap: "anywhere",
              }}
            >
              {c.format}
            </span>
          </div>
        ) : (
          <div style={{ ...sansStyle, fontSize: "0.6875rem", fontWeight: 700, color: ink }}>
            {c.format} - BELOW THE {D.floor.toFixed(1)} FLOOR
            {impossible ? " - IMPOSSIBLE AT THIS HUE" : ""}
          </div>
        )}
        <div style={{ ...monoStyle, color: ink, textAlign: "right" }}>
          {c.hex}
          <br />
          {c.contrast.toFixed(2)}:1
          {extra === null ? null : (
            <>
              <br />
              {extra}
            </>
          )}
        </div>
      </div>
    )
  }

  const halfStyle = (bg: string, ink: string): React.CSSProperties => ({
    width: "100%",
    padding: "0.5rem 1rem 0.75rem",
    background: bg,
    color: ink,
  })

  const bodyStyle: React.CSSProperties = {
    fontFamily: READING_STACK,
    fontSizeAdjust: xheight,
    fontSize: "1.0625rem",
    lineHeight: 1.6,
    margin: "0.1875rem 0 0.5rem",
  }

  return (
    <section style={{ width: "100%", maxWidth: "100%" }}>
      <div style={{ background: CHROME_BG, borderBottom: "1px solid #333333", padding: "0.375rem 0.75rem 0.625rem" }}>
        <h2
          style={{
            ...sansStyle,
            margin: "0 0 0.375rem",
            fontSize: "0.6875rem",
            letterSpacing: "0.12em",
            textTransform: "uppercase",
            fontWeight: 600,
            color: CHROME_DIM,
          }}
        >
          Dark half - which equivalent set ({D.sets.length})
        </h2>
        <div style={{ display: "flex", flexWrap: "wrap", gap: "0.375rem" }}>
          {D.sets.map((s, i) => button(s.name, i === setIndex, () => setSetIndex(i)))}
        </div>
      </div>

      <div id="halfLightEq" style={halfStyle(D.lightGround, LIGHT_INK)}>
        <div style={monoStyle}>
          LIGHT GROUND {D.lightGround} - globals.css line {D.lightGroundLine} - SETTLED, no controls
          - text ink {LIGHT_INK}
        </div>
        <p style={bodyStyle}>{BODY}</p>
        <div style={{ display: "grid", gap: "0.3125rem" }}>
          {D.light.map((c) => row(c, LIGHT_INK, null))}
        </div>
      </div>

      <div id="halfDarkEq" style={halfStyle(D.darkGround, DARK_INK)}>
        <div style={monoStyle}>
          DARK GROUND {D.darkGround} - globals.css line {D.darkGroundLine} - {active.name} - text
          ink {DARK_INK}
          <br />
          {active.blurb}
        </div>
        <p style={bodyStyle}>{BODY}</p>
        <div style={{ display: "grid", gap: "0.3125rem" }}>
          {active.colours.map((c) => row(c, DARK_INK, "d " + c.distanceToCounterpart.toFixed(4)))}
        </div>
        <div style={{ ...monoStyle, marginTop: "0.5rem" }}>
          d = OKLab distance to the light value directly above it. Euclidean in OKLab.
          <br />
          smallest pairwise OKLab distance among the seven:{" "}
          {active.scores.minPairwiseDistance.toFixed(4)} ({active.scores.minPairwiseBetween})
          <br />
          smallest chroma among the seven: {active.scores.minChroma.toFixed(4)} (
          {active.scores.minChromaFormat})
          <br />
          below the {D.floor.toFixed(1)} floor: {active.scores.failures}, of which impossible at
          their hue: {active.scores.impossible}
          <br />
          distance to counterpart, max {active.scores.maxDistanceToCounterpart.toFixed(4)}, mean{" "}
          {active.scores.meanDistanceToCounterpart.toFixed(4)}
        </div>
      </div>

      <div style={{ ...monoStyle, background: CHROME_BG, color: CHROME_HEX, padding: "0.625rem 0.75rem 0.875rem" }}>
        chrome, not part of the specimen: strip {CHROME_BG}, text {CHROME_INK}, idle button{" "}
        {CHROME_BTN} on {CHROME_BTN_EDGE}, pressed button {CHROME_INK} on {CHROME_BTN_ON_INK}, label{" "}
        {CHROME_DIM}, hex {CHROME_HEX}
        <br />
        counts read from the data: {D.sets.length} sets, {D.formats.length} formats,{" "}
        {D.light.length} light values, floor {D.floor}
        <br />
        x-height correction from globals.css: font-size-adjust {xheight}
      </div>
    </section>
  )
}
