"use client"

// THE GROUND-PAIR PANEL. Part of the temporary specimen surface at /specimen,
// not part of the product, and meant to be deleted with the rest of it.
//
// WHY IT IS A PAIR AND NOT TWO PANELS. The rest of the specimen page shows ONE
// ground at a time, chosen by a button. That compares a colour against a memory
// of the last one, which is not the comparison anyone actually needs to make:
// the light theme and the dark theme ship together and are judged together. So
// this panel puts a light ground and a dark ground on the screen AT THE SAME
// TIME, one above the other, both full width, with no switch between them. The
// two are chosen INDEPENDENTLY -- six buttons each, so all thirty-six pairs are
// reachable -- and the palette, the contrast floor and the card treatment are
// chosen once and apply to both halves.
//
// EVERY VALUE COMES FROM ground-palettes-data.ts, which is generated by
// ground-palettes.mjs beside this file and never edited by hand. Nothing here
// computes a colour. That matters because the same blob feeds the standalone
// offline file on the desktop, so the page and that file cannot disagree about
// a hex, and a hex typed in here by hand is a hex that could.
//
// The two usages of an accent are shown SIDE BY SIDE on every row, because the
// choice between the 4.5 and the 3.0 floor is exactly the choice between them:
// 4.5 is required if the accent carries the 11px format name AS TEXT, and 3.0
// is enough if it carries only a rule and a glyph while the name is set in
// ordinary text colour. Reading that as a sentence settles nothing; seeing both
// on one ground does.

import { useState } from "react"

import { PALETTE_DATA, type SpecimenGround } from "./ground-palettes-data"

// The reading face and its x-height correction. The family is the one the
// specimen page's own @font-face block defines; the correction is passed in
// from the page so this file cannot carry a second copy of 0.426 that could
// drift from globals.css. ground-palettes.mjs asserts the two agree.
const READING_STACK = "SpecEBGaramond, serif"

const HEADLINE = "Lise Meitner worked out the arithmetic of fission on a walk through the snow"

const BODY =
  "In December 1938, Otto Hahn wrote to Lise Meitner from Berlin with a result he could not " +
  "explain. He had bombarded uranium with neutrons and found barium in the residue, an element " +
  "with roughly half the atomic mass. Meitner, who had fled to Sweden that July, read the letter " +
  "in Kungalv over Christmas. Walking in the snow with her nephew Otto Frisch, she did the sum on " +
  "a scrap of paper, and the missing fifth of a proton mass came to roughly 200 million electron " +
  "volts per event."

const META = "12 min read - MEDIUM - 4 sources - 2026"

const CARD_TEXT =
  "Bohr had described the nucleus as a liquid drop, and a drop that elongates far enough will " +
  "pinch in two."

// The four treatments from the previous batch, unchanged in kind, so the card
// decision can still be made and can now be made against a chosen PAIR. The
// resolved hexes come from the data blob, which computed the step as the app's
// own #0a0a0a-to-#141414 lightness difference in OKLab.
const CARD_TREATMENTS = ["Step", "Line", "Step and line", "Today, what ships"] as const

function cardStyle(g: SpecimenGround, index: number): { style: React.CSSProperties; label: string } {
  if (index === 0) return { style: { background: g.step }, label: "Step - " + g.step }
  if (index === 1) {
    return { style: { border: "1px solid " + g.rule }, label: "Line - no fill, 1px " + g.rule }
  }
  if (index === 2) {
    return {
      style: { background: g.step, border: "1px solid " + g.rule },
      label: "Step and line - " + g.step + " + 1px " + g.rule,
    }
  }
  return {
    style: { background: g.today },
    label: "Today, what ships - rgb(255 255 255 / 0.04) over " + g.hex + " = " + g.today,
  }
}

// Chrome, deliberately neutral and deliberately labelled with its own hexes:
// this strip is not part of the specimen and must never be mistaken for it.
const CHROME_BG = "#1B1B1B"
const CHROME_INK = "#E8E8E8"
const CHROME_DIM = "#A0A0A0"
const CHROME_HEX = "#8A8A8A"
const CHROME_BTN = "#262626"
const CHROME_BTN_EDGE = "#3A3A3A"
const CHROME_BTN_ON_INK = "#141414"

const monoStyle: React.CSSProperties = {
  fontFamily: "ui-monospace, monospace",
  fontSizeAdjust: "none",
  fontSize: "0.625rem",
  lineHeight: 1.4,
  overflowWrap: "anywhere",
}

const sansStyle: React.CSSProperties = {
  fontFamily: "system-ui, sans-serif",
  fontSizeAdjust: "none",
}

export default function GroundPairPanel({ xheight }: { xheight: string }) {
  const D = PALETTE_DATA
  const [light, setLight] = useState(D.openLight)
  const [dark, setDark] = useState(D.openDark)
  const [palette, setPalette] = useState(0)
  const [floor, setFloor] = useState(D.floors[0])
  const [card, setCard] = useState(0)

  // .concat() and not a slice of a literal. The trap the previous batch
  // recorded was a slice of a TYPED array literal quietly yielding an empty
  // array that looked like success; the counts printed on screen below are what
  // turns that class of failure into a number rather than a blank panel.
  const allGrounds = D.grounds.light.concat(D.grounds.dark)
  const byId = (id: string) => allGrounds.find((g) => g.id === id) ?? allGrounds[0]

  const button = (label: string, hex: string, on: boolean, onClick: () => void) => (
    <button
      key={label + hex}
      type="button"
      onClick={onClick}
      aria-pressed={on}
      style={{
        ...sansStyle,
        minHeight: "44px",
        padding: "0.375rem 0.75rem",
        borderRadius: "0.5rem",
        border: "1px solid " + (on ? CHROME_INK : CHROME_BTN_EDGE),
        background: on ? CHROME_INK : CHROME_BTN,
        color: on ? CHROME_BTN_ON_INK : "#C8C8C8",
        fontSize: "0.75rem",
        fontWeight: on ? 600 : 400,
        lineHeight: 1.2,
        textAlign: "left",
        cursor: "pointer",
      }}
    >
      {label}
      {hex ? (
        <span style={{ ...monoStyle, display: "block", opacity: 0.75 }}>{hex}</span>
      ) : null}
    </button>
  )

  const group = (title: string, children: React.ReactNode) => (
    <div style={{ marginTop: "0.625rem" }}>
      <div
        style={{
          ...sansStyle,
          fontSize: "0.6875rem",
          letterSpacing: "0.12em",
          textTransform: "uppercase",
          fontWeight: 600,
          color: CHROME_DIM,
          marginBottom: "0.375rem",
        }}
      >
        {title}
      </div>
      <div style={{ display: "flex", flexWrap: "wrap", gap: "0.375rem" }}>{children}</div>
    </div>
  )

  // The id is what the DevTools probe beside this file looks for, so the same
  // command measures this panel and the standalone offline file.
  const half = (groundId: string, familyLabel: string, id: string) => {
    const g = byId(groundId)
    const pal = D.palettes[palette]
    const cell = pal.cells[floor][g.id]
    const treatment = cardStyle(g, card)

    return (
      <section id={id} style={{ width: "100%", background: g.hex, color: g.ink, padding: "0.875rem 1rem 1.25rem" }}>
        <div style={{ ...monoStyle, marginBottom: "0.25rem" }}>
          {familyLabel} - {g.id} - {g.hex} - {g.oklch}
          <br />
          {g.derivation}
          <br />
          text ink {g.ink} - palette {pal.name} - floor {floor}
        </div>

        <h2
          style={{
            fontFamily: READING_STACK,
            fontSizeAdjust: xheight,
            fontSize: "2rem",
            fontWeight: 500,
            lineHeight: 1.15,
            letterSpacing: "-0.02em",
            margin: "0.375rem 0 0.625rem",
          }}
        >
          {HEADLINE}
        </h2>

        <p
          style={{
            fontFamily: READING_STACK,
            fontSizeAdjust: xheight,
            fontSize: "1.0625rem",
            lineHeight: 1.7,
            margin: "0 0 0.75rem",
          }}
        >
          {BODY}
        </p>

        <div
          style={{
            ...sansStyle,
            fontSize: "11px",
            letterSpacing: "0.06em",
            textTransform: "uppercase",
            marginBottom: "0.75rem",
          }}
        >
          {META}
        </div>

        <div style={{ padding: "0.75rem", marginBottom: "0.875rem", ...treatment.style }}>
          <p
            style={{
              fontFamily: READING_STACK,
              fontSizeAdjust: xheight,
              fontSize: "1.0625rem",
              lineHeight: 1.6,
              margin: "0 0 0.5rem",
            }}
          >
            {CARD_TEXT}
          </p>
          <div style={{ ...monoStyle, color: g.ink }}>{treatment.label}</div>
        </div>

        <div
          style={{
            ...sansStyle,
            fontSize: "0.625rem",
            letterSpacing: "0.14em",
            textTransform: "uppercase",
            margin: "0.875rem 0 0.375rem",
          }}
        >
          The seven format accents - left: the 11px name set in the accent. right: the name in
          ordinary text colour beside an accent square and a 2px accent rule.
        </div>

        <div style={{ display: "grid", gap: "0.5rem" }}>
          {cell.colours.map((c) => (
            <div
              key={c.format}
              style={{
                display: "grid",
                // minmax(0, ...) on every column: without the zero minimum a
                // grid column refuses to shrink below its content and the page
                // gains a horizontal scrollbar on a narrow phone.
                gridTemplateColumns: "minmax(0, 74px) minmax(0, 1fr) minmax(0, 96px)",
                gap: "0.5rem",
                alignItems: "center",
              }}
            >
              <div
                style={{
                  ...sansStyle,
                  fontSize: "11px",
                  fontWeight: 600,
                  letterSpacing: "0.04em",
                  textTransform: "uppercase",
                  overflowWrap: "anywhere",
                  color: c.ok && c.hex ? c.hex : g.ink,
                }}
              >
                {c.format}
              </div>
              {c.ok && c.hex ? (
                <div style={{ display: "flex", alignItems: "center", gap: "0.375rem", minWidth: 0 }}>
                  <span style={{ width: "12px", height: "12px", flex: "none", background: c.hex }} />
                  <span style={{ width: "26px", height: "2px", flex: "none", background: c.hex }} />
                  <span
                    style={{
                      ...sansStyle,
                      fontSize: "11px",
                      letterSpacing: "0.04em",
                      textTransform: "uppercase",
                      overflowWrap: "anywhere",
                      color: g.ink,
                    }}
                  >
                    {c.format}
                  </span>
                </div>
              ) : (
                <div style={{ ...sansStyle, fontSize: "11px", fontWeight: 700 }}>
                  FAILS the {floor} floor at every lightness
                </div>
              )}
              <div style={monoStyle}>
                {c.ok && c.hex ? c.hex : "-"}
                <br />
                {c.contrast === null ? "-" : c.contrast.toFixed(2)}:1
                <br />
                hue {c.hue.toFixed(1)}
              </div>
            </div>
          ))}
        </div>

        <div style={{ ...monoStyle, marginTop: "0.625rem", lineHeight: 1.5 }}>
          smallest pairwise OKLab distance among the seven:{" "}
          {cell.minDistance === null ? "n/a" : cell.minDistance.toFixed(4)}
          <br />
          smallest chroma among the seven:{" "}
          {cell.minChroma === null ? "n/a" : cell.minChroma.toFixed(4)}
          <br />
          colours failing the floor: {cell.failures}
          <br />
          OKLCH of each:{" "}
          {cell.colours.map((c) => c.format + " " + (c.oklch ?? "-")).join(" | ")}
        </div>
      </section>
    )
  }

  return (
    <div style={{ width: "100%" }}>
      <div style={{ background: CHROME_BG, color: CHROME_INK, padding: "0.75rem 1rem 1rem" }}>
        <div
          style={{
            ...sansStyle,
            fontSize: "0.75rem",
            fontWeight: 600,
            letterSpacing: "0.04em",
            textTransform: "uppercase",
          }}
        >
          Ground pair, palette and floor
        </div>
        {group(
          "Light ground (6)",
          D.grounds.light.map((g) =>
            button(g.id.replace(/^L-/, ""), g.hex, g.id === light, () => setLight(g.id)),
          ),
        )}
        {group(
          "Dark ground (6)",
          D.grounds.dark.map((g) =>
            button(g.id.replace(/^D-/, ""), g.hex, g.id === dark, () => setDark(g.id)),
          ),
        )}
        {group(
          "Palette (4) - both halves",
          D.palettes.map((p, i) => button(p.name, "", i === palette, () => setPalette(i))),
        )}
        {group(
          "Contrast floor (2) - both halves",
          D.floors.map((f) =>
            button(
              f === "4.5"
                ? "4.5 - accent carries the 11px name as text"
                : "3.0 - accent carries only a rule and a glyph",
              "",
              f === floor,
              () => setFloor(f),
            ),
          ),
        )}
        {group(
          "Card treatment (4) - both halves",
          CARD_TREATMENTS.map((t, i) => button(t, "", i === card, () => setCard(i))),
        )}
        <div style={{ ...monoStyle, color: CHROME_HEX, marginTop: "0.625rem" }}>
          chrome, not part of the specimen: strip {CHROME_BG}, text {CHROME_INK}, idle button{" "}
          {CHROME_BTN} on {CHROME_BTN_EDGE}, pressed button {CHROME_INK} on {CHROME_BTN_ON_INK},
          label {CHROME_DIM}, hex {CHROME_HEX}
          <br />
          counts read from the data: {allGrounds.length} grounds, {D.palettes.length} palettes,{" "}
          {D.floors.length} floors, {D.formats.length} formats
          <br />
          x-height correction read from globals.css: font-size-adjust {xheight}
          <br />
          {D.palettes[palette].note}
        </div>
      </div>

      {half(light, "LIGHT GROUND", "halfLight")}
      {half(dark, "DARK GROUND", "halfDark")}
    </div>
  )
}
